# Generated by Django 5.2 on 2025-04-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='artist_image',
            field=models.ImageField(blank=True, null=True, upload_to='artists/'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='artist',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='concert',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='concert',
            name='venue',
            field=models.CharField(max_length=255),
        ),
    ]
